### PR TITLE
zig: upgrade to 0.12.0-dev.2043+6ebeb85ab

### LINKED ISSUE #133: lstat error does not set errno
The following code does not work for me with this toolchain:

```
#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <errno.h>
#include <stdbool.h>

bool fileOrDirExists(const char *path) {
    struct stat statbuf;

    if (lstat(path, &statbuf) == -1) {
        if (errno == ENOENT) {
            // File or directory does not exist
            return false;
        } else {
            // An error other than ENOENT occurred, crash the program
            perror("Unexpected error occurred in lstat");
            exit(EXIT_FAILURE);
        }
    }

    // File or directory exists
    return true;
}

int main() {
    const char *path = "/tmp/i-dont-exist";  // Replace with your path

    if (fileOrDirExists(path)) {
        printf("The path '%s' exists.\n", path);
    } else {
        printf("The path '%s' does not exist.\n", path);
    }

    return 0;
}
````

### Expected output:
```
The path '/tmp/i-dont-exist' does not exist.
```

### Actual output:
```
Unexpected error occurred in lstat: Success
```

# Repro steps:

```
git clone https://github.com/juanique/bazel-examples --branch=error_repro_lstat_f5cf2
cd bazel-examples/bazel6/rules_cc/4-zig-hermetic-cc-toolchain
bazel run :main

Unexpected error occurred in lstat: Success
````

Compare to result using `gcc-hermetic-toolchain` from aspect.dev: 

```
git clone https://github.com/juanique/bazel-examples --branch=error_repro_lstat_f5cf2
cd bazel-examples/bazel6/rules_cc/3-aspect-gcc-toolchain
bazel run :main

The path '/tmp/i-dont-exist' does not exist.
````

- I'm using WSL2 on windows.
- Seems to work fine for me on MacOS arm64. 
- I haven't checked on regular Linux yet

### PR DESCRIPTION
**Pull request by motiejus-wix**
Notable changes:
- bump glibc support from 2.34 to 2.38
- fix integration with some glibc symbols:   https://github.com/ziglang/zig/pull/17702
- mitigat `error: AccessDenied`, which, according to Noah Santschi-Cooney, also mitigates/fixes the dreaded `error: FileNotFound` which we sometimes see when setting up Bazel worksace. Relevant commit in Zig: https://github.com/ziglang/zig/commit/6b2709616e22e7651f16293034cc0d25f0e9be0a

Fixes #133

### CODE REVIEW

**Comment by motiejus** [comment]
https://github.com/bazelbuild/bazel/issues/20751

**Comment by motiejus-wix** [comment]
Can you paste the full workspace, with zlib srcs, or something where I can repro this fully?

**Comment by linzhp** [comment]
You can build `@zlib//:zlib-static-lib` out of this workspace:

```
-- BUILD.bazel --
-- WORKSPACE --
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "hermetic_cc_toolchain",
    sha256 = "2eeb06a1996165575c1d13654ca178f8ba3ef34aae44f0afb201c5ac15181c68",
    strip_prefix = "hermetic_cc_toolchain-13b6062c668baf1d661de8a23230eb13c546b2ce",
    urls = [
        "https://github.com/uber/hermetic_cc_toolchain/archive/13b6062c668baf1d661de8a23230eb13c546b2ce.zip",
    ],
)

load("@hermetic_cc_toolchain//toolchain:defs.bzl", zig_toolchains = "toolchains")

# Plain zig_toolchains() will pick reasonable defaults. See
# toolchain/defs.bzl:toolchains on how to change the Zig SDK version and
# download URL.
zig_toolchains()

http_archive(
    name = "zlib",
    build_file = "//:zlib.build",
    sha256 = "b3a24de97a8fdbc835b9833169501030b8977031bcb54b3b3ac13740f846ab30",
    strip_prefix = "zlib-1.2.13",
    urls = [
        "https://storage.googleapis.com/mirror.tensorflow.org/zlib.net/zlib-1.2.13.tar.gz",
    ],
)

rules_foreign_cc_version = "a87e7542ee893ba1d8f3dd1505f9af10a308db92"

http_archive(
    name = "rules_foreign_cc",
    sha256 = "0abb19a1a169af5abb3801f80709895588bf2f6f6009d3af71a35152a583e6d0",
    strip_prefix = "rules_foreign_cc-{}".format(rules_foreign_cc_version),
    urls = [
        "https://github.com/bazelbuild/rules_foreign_cc/archive/{}.tar.gz".format(rules_foreign_cc_version),
    ],
)

load("@rules_foreign_cc//foreign_cc:repositories.bzl", "rules_foreign_cc_dependencies")

rules_foreign_cc_dependencies()
-- zlib.build --
load("@rules_foreign_cc//foreign_cc:defs.bzl", "cmake")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "all_srcs",
    srcs = glob(
        include = ["**"],
        exclude = ["*.bazel"],
    ),
)

cmake(
    name = "zlib-static-lib",
    cache_entries = select({
        "@platforms//os:linux": {
            "CMAKE_C_FLAGS": "${CMAKE_C_FLAGS:-} -fPIC",
        },
        "//conditions:default": {},
    }),
    generate_args = [],
    lib_source = "all_srcs",
    out_static_libs = ["libz.a"],
)
```

**Comment by motiejus-wix** [comment]
Just reproduced this without bazel:

```
wget https://storage.googleapis.com/mirror.tensorflow.org/zlib.net/zlib-1.2.13.tar.gz
tar -xf zlib*.gz
cd zlib-*
mkdir build; cd build
CC="zig cc -target x86_64-linux-gnu.2.28" cmake ..
make
<...>
Consolidate compiler generated dependencies of target zlib
[  2%] Linking C shared library libz.so
LLD Link... ld.lld: error: version script assignment of 'local' to symbol 'gz_intmax' failed: symbol not defined
make[2]: *** [CMakeFiles/zlib.dir/build.make:321: libz.so.1.2.13] Error 1
make[1]: *** [CMakeFiles/Makefile2:93: CMakeFiles/zlib.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

**Comment by motiejus** [comment]
Works with `zld` though:

```
motiejus@mtwork:~/x/zlib-1.3/build$ CC="$HOME/code/zig/build/stage4/bin/zig cc -Wl,--no-lld -target x86_64-linux-gnu.2.28" cmake ..
-- The C compiler identification is Clang 17.0.6
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /home/motiejus/code/zig/build/stage4/bin/zig - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of off64_t
-- Check size of off64_t - done
-- Looking for fseeko
-- Looking for fseeko - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/motiejus/x/zlib-1.3/build
motiejus@mtwork:~/x/zlib-1.3/build$ make
[  2%] Building C object CMakeFiles/zlib.dir/adler32.c.o
[  5%] Building C object CMakeFiles/zlib.dir/compress.c.o
[  7%] Building C object CMakeFiles/zlib.dir/crc32.c.o
[ 10%] Building C object CMakeFiles/zlib.dir/deflate.c.o
[ 12%] Building C object CMakeFiles/zlib.dir/gzclose.c.o
[ 15%] Building C object CMakeFiles/zlib.dir/gzlib.c.o
[ 17%] Building C object CMakeFiles/zlib.dir/gzread.c.o
[ 20%] Building C object CMakeFiles/zlib.dir/gzwrite.c.o
[ 22%] Building C object CMakeFiles/zlib.dir/inflate.c.o
[ 25%] Building C object CMakeFiles/zlib.dir/infback.c.o
[ 27%] Building C object CMakeFiles/zlib.dir/inftrees.c.o
[ 30%] Building C object CMakeFiles/zlib.dir/inffast.c.o
[ 32%] Building C object CMakeFiles/zlib.dir/trees.c.o
[ 35%] Building C object CMakeFiles/zlib.dir/uncompr.c.o
[ 37%] Building C object CMakeFiles/zlib.dir/zutil.c.o
[ 40%] Linking C shared library libz.so
[ 40%] Built target zlib
[ 42%] Building C object CMakeFiles/zlibstatic.dir/adler32.c.o
[ 45%] Building C object CMakeFiles/zlibstatic.dir/compress.c.o
[ 47%] Building C object CMakeFiles/zlibstatic.dir/crc32.c.o
[ 50%] Building C object CMakeFiles/zlibstatic.dir/deflate.c.o
[ 52%] Building C object CMakeFiles/zlibstatic.dir/gzclose.c.o
[ 55%] Building C object CMakeFiles/zlibstatic.dir/gzlib.c.o
[ 57%] Building C object CMakeFiles/zlibstatic.dir/gzread.c.o
[ 60%] Building C object CMakeFiles/zlibstatic.dir/gzwrite.c.o
[ 62%] Building C object CMakeFiles/zlibstatic.dir/inflate.c.o
[ 65%] Building C object CMakeFiles/zlibstatic.dir/infback.c.o
[ 67%] Building C object CMakeFiles/zlibstatic.dir/inftrees.c.o
[ 70%] Building C object CMakeFiles/zlibstatic.dir/inffast.c.o
[ 72%] Building C object CMakeFiles/zlibstatic.dir/trees.c.o
[ 75%] Building C object CMakeFiles/zlibstatic.dir/uncompr.c.o
[ 77%] Building C object CMakeFiles/zlibstatic.dir/zutil.c.o
[ 80%] Linking C static library libz.a
[ 80%] Built target zlibstatic
[ 82%] Building C object CMakeFiles/example.dir/test/example.c.o
[ 85%] Linking C executable example
[ 85%] Built target example
[ 87%] Building C object CMakeFiles/minigzip.dir/test/minigzip.c.o
[ 90%] Linking C executable minigzip
[ 90%] Built target minigzip
[ 92%] Building C object CMakeFiles/example64.dir/test/example.c.o
[ 95%] Linking C executable example64
[ 95%] Built target example64
[ 97%] Building C object CMakeFiles/minigzip64.dir/test/minigzip.c.o
[100%] Linking C executable minigzip64
[100%] Built target minigzip64
motiejus@mtwork:~/x/zlib-1.3/build$ 
```

With the following changes to `zig`:

```patch
diff --git a/src/main.zig b/src/main.zig
index 4442234bd..6c440770c 100644
--- a/src/main.zig
+++ b/src/main.zig
@@ -898,6 +898,7 @@ fn buildOutputType(
     var rc_includes: Compilation.RcIncludes = .any;
     var manifest_file: ?[]const u8 = null;
     var linker_export_symbol_names: std.ArrayListUnmanaged([]const u8) = .{};
+    var use_lld: ?bool = null;
 
     // Tracks the position in c_source_files which have already their owner populated.
     var c_source_files_owner_index: usize = 0;
@@ -1928,6 +1929,10 @@ fn buildOutputType(
                             }
                             if (mem.eql(u8, linker_arg, "--build-id")) {
                                 build_id = .fast;
+                            } else if (mem.eql(u8, linker_arg, "--no-lld")) {
+                                use_lld = false;
+                            } else if (mem.eql(u8, linker_arg, "--use-lld")) {
+                                use_lld = true;
                             } else if (mem.eql(u8, linker_arg, "--as-needed")) {
                                 needed = false;
                             } else if (mem.eql(u8, linker_arg, "--no-as-needed")) {
@@ -2683,6 +2688,7 @@ fn buildOutputType(
     create_module.opts.emit_llvm_ir = emit_llvm_ir != .no;
     create_module.opts.emit_llvm_bc = emit_llvm_bc != .no;
     create_module.opts.emit_bin = emit_bin != .no;
+    create_module.opts.use_lld = use_lld;
     create_module.opts.any_c_source_files = create_module.c_source_files.items.len != 0;
 
     const main_mod = try createModule(gpa, arena, &create_module, 0, null, zig_lib_directory);
```

**Comment by motiejus** [comment]
Seems like a workaround is here: https://github.com/madler/zlib/pull/865

cc @linzhp

**Review by linzhp — APPROVED** [review]
Just tested this with https://github.com/madler/zlib/pull/865 in Uber. Everything passed.

**Pull request merged**
