### PR TITLE
Strip the zig-builder binary for reproducibility

### PR DESCRIPTION
**Pull request by dzbarsky**
Prior to this, I noticed builds ending up with different digests for the builder fairly often. Stripping those builder binaries manually made them match up; with this patch applied, I was able to have builds be 100% cached when trying 5 times (previously almost every time was a different digest).

### CODE REVIEW

**Comment by motiejus** [comment]
Did you validate it does become reproducible after this change? Please update the commit message with more details.

Code-wise lgtm

**Comment by dzbarsky** [comment]
Yes, it looks reproducible to me; updated the summary.

**Comment by motiejus** [comment]
> Yes, it looks reproducible to me; updated the summary.

This is good, thanks. Please rebase and add the description to the commit.

I noticed the release tests are broken, at some point we will take action on those. I cannot make any concrete time promises, but we will get to it.

**Review by motiejus — APPROVED** [review]

**Comment by motiejus** [comment]
Thanks!

**Pull request merged**
