### PR TITLE
Add windows aliases

### PR DESCRIPTION
**Pull request by motiejus**
This adds non-exe aliases to user-facing executables:

             :tools/ar  -> :tools/ar.exe
         :tools/ld.lld  -> :tools/ld.lld.exe
       :tools/lld-link  -> :tools/lld-link.exe
    :tools/zig-wrapper  -> :tools/zig-wrapper.exe

... so they can be used in either OSs without caring of the file extension.

tools

### CODE REVIEW

**Review by laurynaslubys — APPROVED** [review]
Should we just always use the non suffixed versions 
instead?

**Review by laurynaslubys — APPROVED** [review]
Should we just always use the non suffixed versions 
instead?

**Comment by motiejus** [comment]
> Should we just always use the non suffixed versions instead?

Are you referring to `c++.exe`?

The files will need to be there anyway, since AFAIK Windows is not good with executing things without a suffix.

If you are referring to other files but `c++.exe`, please clarify.

**Review by FabianHahn — APPROVED** [review]
LGTM

**Pull request merged**
